[build]
builder = "dockerfile"

# Only deploy on ReleasePlease release
watchPatterns = [".release-please-manifest.json"]

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 30
sleepApplication = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
numReplicas = 1
